updates

diff --git a/.github/workflows/build-dev.yml b/.github/workflows/build-dev.yml
--- a/.github/workflows/build-dev.yml
+++ b/.github/workflows/build-dev.yml
@@ -13,7 +13,7 @@ jobs:
     strategy:
       matrix:
         node-version: [18.x, 20.x, 22.x]
-        homebridge-version: ["^1.6.0", "^1.8.0", "^2.0.0-beta.0"]
+        homebridge-version: ["~1.6.0", "~1.8.0", "^2.0.0-beta.0"]
 
     steps:
       - uses: actions/checkout@v4
@@ -38,13 +38,13 @@ jobs:
       - name: Build the project
         run: npm run build
 
-      # - name: List, audit, fix outdated dependencies and build again
-      #   run: |
-      #     npm list --outdated
-      #     npm audit || true  # ignore failures
-      #     npm audit fix || true
-      #     npm list --outdated
-      #     npm run build
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          npm list --outdated
+          npm audit || true  # ignore failures
+          npm audit fix || true
+          npm list --outdated
+          npm run build
 
       - name: Run the tests
         run: npm test
